local wezterm = require("wezterm")
---@type table<string, string>
local nf = wezterm.nerdfonts

---@type table<string, string>
local dividers = {
	["soft_right"] = nf.pl_right_soft_divider,
	["soft_left"] = nf.pl_left_soft_divider,
	["hard_right"] = nf.pl_right_hard_divider,
	["hard_left"] = nf.pl_left_hard_divider,
	["heart"] = nf.oct_heart,
}

---@type table<string, string>
local dev_icons = {
	["default"] = nf.fa_terminal,
	["folder"] = nf.md_folder,
	["clock"] = nf.md_clock_outline,
	["Charging"] = nf.fa_plug,
	["docker"] = nf.linux_docker,
	["docker-compose"] = nf.linux_docker,
	["psql"] = nf.dev_postgresql,
	["kuberlr"] = nf.linux_docker,
	["kubectl"] = nf.linux_docker,
	["stern"] = nf.linux_docker,
	["nvim"] = nf.custom_vim,
	["make"] = nf.seti_makefile,
	["vim"] = nf.dev_vim,
	["vi"] = nf.dev_vim,
	["go"] = nf.seti_go,
	["zsh"] = nf.dev_terminal,
	["bash"] = nf.cod_terminal_bash,
	["btm"] = nf.mdi_chart_donut_variant,
	["htop"] = nf.mdi_chart_donut_variant,
	["cargo"] = nf.dev_rust,
	["sudo"] = nf.fa_hashtag,
	["lazydocker"] = nf.linux_docker,
	["git"] = nf.dev_git,
	["lua"] = nf.seti_lua,
	["wget"] = nf.mdi_arrow_down_box,
	["curl"] = nf.mdi_flattr,
	["gh"] = nf.dev_github_badge,
	["ruby"] = nf.cod_ruby,
	["pwsh"] = nf.seti_powershell,
	["node"] = nf.dev_nodejs_small,
	["dotnet"] = nf.md_language_csharp,
	["fish"] = nf.md_fish,
	["mongo"] = nf.dev_mongodb,
	["ssh"] = nf.md_ssh,
	["python"] = nf.dev_python,
	["admin"] = nf.oct_shield,
	["lambda"] = nf.md_lambda,
	["left_arrow"] = nf.md_arrow_left,
	["right_arrow"] = nf.md_arrow_right,
	["java"] = nf.dev_java,
}

local tab_numbers = {
	sup_idx = {
		"¹",
		"²",
		"³",
		"⁴",
		"⁵",
		"⁶",
		"⁷",
		"⁸",
		"⁹",
		"¹⁰",
		"¹¹",
		"¹²",
		"¹³",
		"¹⁴",
		"¹⁵",
		"¹⁶",
		"¹⁷",
		"¹⁸",
		"¹⁹",
		"²⁰",
	},
	sub_idx = {
		"₁",
		"₂",
		"₃",
		"₄",
		"₅",
		"₆",
		"₇",
		"₈",
		"₉",
		"₁₀",
		"₁₁",
		"₁₂",
		"₁₃",
		"₁₄",
		"₁₅",
		"₁₆",
		"₁₇",
		"₁₈",
		"₁₉",
		"₂₀",
	},
}

---@type table<string, string | table<number, string>>
local battery = {
	["Full"] = nf.md_battery_heart,
	["Discharging"] = {
		[0.1] = nf.md_battery_alert_variant_outline,
		[0.2] = nf.md_battery_20,
		[0.3] = nf.md_battery_30,
		[0.4] = nf.md_battery_40,
		[0.5] = nf.md_battery_50,
		[0.6] = nf.md_battery_60,
		[0.7] = nf.md_battery_70,
		[0.8] = nf.md_battery_80,
		[0.9] = nf.md_battery_90,
		[1] = nf.md_battery_90,
	},
	["Charging"] = {
		[0.1] = nf.md_battery_charging_10,
		[0.2] = nf.md_battery_charging_20,
		[0.3] = nf.md_battery_charging_30,
		[0.4] = nf.md_battery_charging_40,
		[0.5] = nf.md_battery_charging_50,
		[0.6] = nf.md_battery_charging_60,
		[0.7] = nf.md_battery_charging_70,
		[0.8] = nf.md_battery_charging_80,
		[0.9] = nf.md_battery_charging_90,
		[1] = nf.md_battery_charging_90,
	},
}

return {
	dev_icons = dev_icons,
	tab_numbers = tab_numbers,
	battery = battery,
	dividers = dividers,
}
